### ISSUE TITLE
HiGrow accuracy or missing calibration

### ISSUE THREAD

**Issue by ro85ac** [Xinyuan-LilyGO/LilyGo-HiGrow#51]
I have 4 HiGrow board and all have the same issue:
- If I put Higrow in a glass of water the **Soil Value** is always around 65%, when the expected value should be 100%
- If I take it out of the water the **Soil Value** is 22%, when the expected value should be 0%
@LilyGO @lewisxhe Is the soil sensor accuracy low or am I missing a calibration?

As a note: I made the same test with Xiaomi Soil Sensor and the values are correct.
https://www.aliexpress.com/item/32848400991.html

![IMG_9874](https://user-images.githubusercontent.com/11976725/148661766-3c6a779f-ca06-4419-a0e2-dabcbcf16855.jpg)
![IMG_9876](https://user-images.githubusercontent.com/11976725/148661769-75f6b9fa-0417-44b2-a9d5-e7ac0bbc4f2e.jpg)

**Comment by ro85ac** [comment]
After digging more I found that you calculate the soil moisture using method map from WMath.cpp
`long map(long x, long in_min, long in_max, long out_min, long out_max)`

And you are mapping like this: `map(soil, 0, 4095, 100, 0);`

@LilyGO  @lewisxhe Why did you send the parameters 0 and 4095 when the actual values read by the sensor are ~1475 (min) and ~3280 (max)?

**Comment by LilyGO** [comment]
> After digging more I found that you calculate the soil moisture using method map from WMath.cpp `long map(long x, long in_min, long in_max, long out_min, long out_max)`
> 
> And the actual code is: `map(soil, 0, 4095, 100, 0);`
> 
> @LilyGO @lewisxhe Why did you send the parameters 0 and 4095 when the actual values read by the sensor are ~1475 (min) and ~3280 (max)?

Because the soil medium is different, it is impossible to do a unified calibration.
